### PR TITLE
Update to kernel 6.9.3

### PR DESCRIPTION
**Pull request by WorldofShadows**
Updated to kernel 6.9.3, compiled, installed and runs without any problems:
`uname -a
Linux hyperion 6.9.3-arch1-1-vivepro2 #1 SMP PREEMPT_DYNAMIC Sun, 02 Jun 2024 17:32:15 +0000 x86_64 GNU/Linux`

### CODE REVIEW

**Comment by RononDex** [comment]
Thank you very much for the PR :) just added one small coment

**Comment by WorldofShadows** [comment]
Honestly, i don't see it :D What did i miss? :) Still trying to figure most of the stuff out here.

**Comment by RononDex** [comment]
According to the Pull request you also changed the url here:
image

**Comment by RononDex** [comment]
Ah also just noticed you also changed the maintainer at top, which is fine I guess but then you should not merge it with the main repository :)

**Comment by WorldofShadows** [comment]
Ah, okay, now i see it! :) 
I pulled the kernel with 'pkgctl repo clone --protocol=https linux' over the Arch build system and simply forgot the comments and maintainer and honestly overlooked the url when editing the PKGBUILD. My bad. 
But noted for the next kernel!
Thank you :)

**Comment by RononDex** [comment]
Closing since PR is now obsolete, already upgraded to kernel 6.10.2

**Pull request closed without merging**
